// Curated major-city lists per country. Not exhaustive (a full world-cities
// database is 150k+ rows — impractical to ship for a dropdown), but covers
// every African country plus every other major market. getCitiesForCountry
// returns [] for anything not listed here, and callers should fall back to
// a free-text city input in that case rather than showing an empty list.
export const CITIES_BY_COUNTRY = {
  Algeria: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Batna'],
  Angola: ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Lubango'],
  Benin: ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou'],
  Botswana: ['Gaborone', 'Francistown', 'Molepolole', 'Maun'],
  'Burkina Faso': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou'],
  Burundi: ['Bujumbura', 'Gitega', 'Ngozi'],
  'Cabo Verde': ['Praia', 'Mindelo'],
  Cameroon: ['Douala', 'Yaoundé', 'Garoua', 'Bamenda'],
  'Central African Republic': ['Bangui', 'Bimbo'],
  Chad: ["N'Djamena", 'Moundou', 'Sarh'],
  Comoros: ['Moroni'],
  'Congo (Brazzaville)': ['Brazzaville', 'Pointe-Noire'],
  'Congo (DRC)': ['Kinshasa', 'Lubumbashi', 'Goma', 'Bukavu'],
  "Côte d'Ivoire": ['Abidjan', 'Bouaké', 'Yamoussoukro', 'San-Pédro'],
  Djibouti: ['Djibouti City'],
  Egypt: ['Cairo', 'Alexandria', 'Giza', 'Luxor', 'Aswan', 'Sharm El Sheikh'],
  'Equatorial Guinea': ['Malabo', 'Bata'],
  Eritrea: ['Asmara', 'Keren'],
  Eswatini: ['Mbabane', 'Manzini'],
  Ethiopia: ['Addis Ababa', 'Dire Dawa', 'Bahir Dar', 'Mekelle'],
  Gabon: ['Libreville', 'Port-Gentil'],
  Gambia: ['Banjul', 'Serekunda'],
  Ghana: ['Accra', 'Kumasi', 'Tamale', 'Takoradi', 'Cape Coast'],
  Guinea: ['Conakry', 'Nzérékoré'],
  'Guinea-Bissau': ['Bissau'],
  Kenya: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
  Lesotho: ['Maseru'],
  Liberia: ['Monrovia'],
  Libya: ['Tripoli', 'Benghazi', 'Misrata'],
  Madagascar: ['Antananarivo', 'Toamasina', 'Antsirabe'],
  Malawi: ['Lilongwe', 'Blantyre', 'Mzuzu'],
  Mali: ['Bamako', 'Sikasso'],
  Mauritania: ['Nouakchott'],
  Mauritius: ['Port Louis', 'Curepipe'],
  Morocco: ['Casablanca', 'Rabat', 'Marrakesh', 'Fez', 'Tangier', 'Agadir'],
  Mozambique: ['Maputo', 'Matola', 'Beira', 'Nampula'],
  Namibia: ['Windhoek', 'Walvis Bay', 'Swakopmund'],
  Niger: ['Niamey', 'Zinder'],
  Nigeria: ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City'],
  Rwanda: ['Kigali', 'Butare', 'Gisenyi'],
  'Sao Tome and Principe': ['São Tomé'],
  Senegal: ['Dakar', 'Touba', 'Thiès', 'Saint-Louis'],
  Seychelles: ['Victoria'],
  'Sierra Leone': ['Freetown', 'Bo'],
  Somalia: ['Mogadishu', 'Hargeisa'],
  'South Africa': [
    'Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth',
    'Bloemfontein', 'East London', 'Polokwane', 'Nelspruit', 'Kimberley',
    'Rustenburg', 'Pietermaritzburg', 'Stellenbosch', 'George', 'Soweto',
  ],
  'South Sudan': ['Juba'],
  Sudan: ['Khartoum', 'Omdurman', 'Port Sudan'],
  Tanzania: ['Dar es Salaam', 'Dodoma', 'Arusha', 'Mwanza', 'Zanzibar City'],
  Togo: ['Lomé', 'Sokodé'],
  Tunisia: ['Tunis', 'Sfax', 'Sousse'],
  Uganda: ['Kampala', 'Gulu', 'Mbarara', 'Jinja'],
  Zambia: ['Lusaka', 'Kitwe', 'Ndola', 'Livingstone'],
  Zimbabwe: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare'],

  India: [
    'Mumbai', 'Delhi', 'Bengaluru', 'Hyderabad', 'Chennai', 'Kolkata',
    'Pune', 'Ahmedabad', 'Jaipur', 'Surat', 'Lucknow', 'Goa', 'Chandigarh',
    'Kochi', 'Indore',
  ],
  'United States': [
    'New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco',
    'Miami', 'Seattle', 'Boston', 'Austin', 'Atlanta', 'Dallas', 'Denver',
  ],
  'United Kingdom': ['London', 'Manchester', 'Birmingham', 'Edinburgh', 'Glasgow', 'Liverpool', 'Bristol'],
  'United Arab Emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman'],
  Canada: ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa'],
  Australia: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'],
  Germany: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne'],
  France: ['Paris', 'Marseille', 'Lyon', 'Nice', 'Toulouse'],
  Italy: ['Rome', 'Milan', 'Naples', 'Turin', 'Florence'],
  Spain: ['Madrid', 'Barcelona', 'Valencia', 'Seville'],
  Netherlands: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'],
  Portugal: ['Lisbon', 'Porto', 'Braga'],
  Switzerland: ['Zurich', 'Geneva', 'Basel', 'Bern'],
  Sweden: ['Stockholm', 'Gothenburg', 'Malmö'],
  Norway: ['Oslo', 'Bergen'],
  Denmark: ['Copenhagen', 'Aarhus'],
  Ireland: ['Dublin', 'Cork', 'Galway'],
  Poland: ['Warsaw', 'Kraków', 'Gdańsk'],
  Turkey: ['Istanbul', 'Ankara', 'Izmir', 'Antalya'],
  Greece: ['Athens', 'Thessaloniki'],
  China: ['Beijing', 'Shanghai', 'Shenzhen', 'Guangzhou', 'Chengdu'],
  Japan: ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama'],
  'South Korea': ['Seoul', 'Busan', 'Incheon'],
  Singapore: ['Singapore'],
  Malaysia: ['Kuala Lumpur', 'Penang', 'Johor Bahru'],
  Indonesia: ['Jakarta', 'Surabaya', 'Bandung', 'Bali (Denpasar)'],
  Philippines: ['Manila', 'Cebu City', 'Davao City'],
  Thailand: ['Bangkok', 'Chiang Mai', 'Phuket'],
  Vietnam: ['Ho Chi Minh City', 'Hanoi', 'Da Nang'],
  Pakistan: ['Karachi', 'Lahore', 'Islamabad'],
  Bangladesh: ['Dhaka', 'Chittagong'],
  'Sri Lanka': ['Colombo', 'Kandy'],
  Nepal: ['Kathmandu', 'Pokhara'],
  'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina'],
  Qatar: ['Doha'],
  Kuwait: ['Kuwait City'],
  Bahrain: ['Manama'],
  Oman: ['Muscat'],
  Jordan: ['Amman'],
  Lebanon: ['Beirut'],
  Israel: ['Tel Aviv', 'Jerusalem', 'Haifa'],
  Iran: ['Tehran', 'Isfahan', 'Shiraz'],
  Iraq: ['Baghdad', 'Erbil', 'Basra'],
  Russia: ['Moscow', 'Saint Petersburg', 'Novosibirsk'],
  Ukraine: ['Kyiv', 'Kharkiv', 'Odesa'],
  Brazil: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'],
  Argentina: ['Buenos Aires', 'Córdoba', 'Rosario'],
  Mexico: ['Mexico City', 'Guadalajara', 'Monterrey', 'Cancún'],
  Chile: ['Santiago', 'Valparaíso'],
  Colombia: ['Bogotá', 'Medellín', 'Cali'],
  Peru: ['Lima', 'Cusco'],
  'New Zealand': ['Auckland', 'Wellington', 'Christchurch'],
  Fiji: ['Suva'],
}

export function getCitiesForCountry(countryName) {
  return CITIES_BY_COUNTRY[countryName] || []
}
