const DEFAULT_COPY = {
  noun: 'business',
  nounPossessive: "business's",
  nameLabel: 'Business name',
  specialtyLabel: 'Business type',
  specialtyPlaceholder: 'e.g. Services, products, specialty',
  specialtyPreview: 'Type',
  descriptionLabel: 'Business description',
  descriptionPlaceholder: 'Tell customers what you do and what makes you stand out.',
  websitePlaceholder: 'www.yourbusiness.com',
  emailPlaceholder: 'hello@yourbusiness.com',
  fallbackName: 'Your business',
  cta: 'Get in touch',
  ctaShort: 'Contact',
  secondaryCta: 'Learn more',
  welcomeLine: (name) => `See what makes ${name} special.`,
  flavorLine: (specialty) =>
    specialty ? `${specialty}, delivered with care.` : 'Quality service, delivered with care.',
  slugExtras: (base) => [`the-${base}`, `${base}-hq`, `${base}-online`],
  signupDescription:
    'Create your owner account, then our onboarding wizard builds your digital presence.',
  signupDeliverables: [
    'Services, bookings & customers in one dashboard',
    'Branded website live in minutes',
    'QR codes, One Link & analytics built in',
    'Payments, reviews & marketing tools',
  ],
  signupQuote:
    '"IROAS cut our onboarding to a single afternoon. Our site, QR and bookings just work."',
  signupPersonName: 'Aarav Kapoor',
  signupPersonRole: 'Owner',
  signupPersonInitials: 'AK',
}

const BY_CATEGORY = {
  Restaurant: {
    noun: 'restaurant',
    nounPossessive: "restaurant's",
    nameLabel: 'Restaurant name',
    specialtyLabel: 'Cuisine type',
    specialtyPlaceholder: 'Search cuisines',
    specialtyPreview: 'Cuisine',
    descriptionLabel: 'Restaurant description',
    descriptionPlaceholder:
      'A modern bistro serving seasonal small plates and natural wine in the heart of downtown.',
    websitePlaceholder: 'www.yourrestaurant.com',
    emailPlaceholder: 'hello@yourrestaurant.com',
    fallbackName: 'Your restaurant',
    cta: 'Reserve a table',
    ctaShort: 'Reserve',
    secondaryCta: 'View menu',
    welcomeLine: (name) => `Taste what makes ${name} special.`,
    flavorLine: (specialty) =>
      specialty ? `${specialty} flavors, crafted with care.` : 'Fresh flavors, crafted with care.',
    slugExtras: (base) => [
      `${base}-kitchen`,
      `eat-${base}`,
      `${base}-dine`,
      `${base}-eats`,
      `${base}-table`,
    ],
    signupDeliverables: [
      'Menu, orders & tables in one dashboard',
      'Branded ordering website in minutes',
      'QR codes, KDS & analytics built in',
      'Payments, reviews & marketing tools',
    ],
    signupQuote:
      '"IROAS cut our onboarding to a single afternoon. Orders, QR menus and staff scheduling just work."',
    signupPersonRole: 'Owner, Saffron & Fig',
  },
  'Retail Store': {
    noun: 'store',
    nounPossessive: "store's",
    nameLabel: 'Store name',
    specialtyLabel: 'Product categories',
    specialtyPlaceholder: 'e.g. Apparel, home, grocery',
    specialtyPreview: 'Products',
    descriptionLabel: 'Store description',
    descriptionPlaceholder: 'A neighborhood store with curated everyday essentials.',
    websitePlaceholder: 'www.yourstore.com',
    emailPlaceholder: 'hello@yourstore.com',
    fallbackName: 'Your store',
    cta: 'Shop now',
    ctaShort: 'Shop',
    secondaryCta: 'Browse products',
    welcomeLine: (name) => `Discover what's new at ${name}.`,
    flavorLine: (specialty) =>
      specialty ? `${specialty} — find your next favorite.` : 'Find your next favorite.',
    slugExtras: (base) => [`${base}-shop`, `${base}-store`, `${base}-mart`],
    signupDeliverables: [
      'Catalog, inventory & orders in one dashboard',
      'Branded shop website in minutes',
      'QR storefront, POS & analytics built in',
      'Payments, reviews & marketing tools',
    ],
    signupQuote:
      '"We launched a shop site and QR storefront the same day we signed up. Stock and orders finally live in one place."',
    signupPersonName: 'Meera Shah',
    signupPersonRole: 'Owner, Olive & Oak',
    signupPersonInitials: 'MS',
  },
  Salon: {
    noun: 'salon',
    nounPossessive: "salon's",
    nameLabel: 'Salon name',
    specialtyLabel: 'Services',
    specialtyPlaceholder: 'e.g. Hair, nails, spa',
    specialtyPreview: 'Services',
    descriptionLabel: 'Salon description',
    descriptionPlaceholder: 'A modern salon for cuts, color, and treatments.',
    websitePlaceholder: 'www.yoursalon.com',
    emailPlaceholder: 'hello@yoursalon.com',
    fallbackName: 'Your salon',
    cta: 'Book an appointment',
    ctaShort: 'Book',
    secondaryCta: 'View services',
    welcomeLine: (name) => `Look your best at ${name}.`,
    flavorLine: (specialty) =>
      specialty ? `${specialty} — tailored to you.` : 'Treatments tailored to you.',
    slugExtras: (base) => [`${base}-salon`, `${base}-studio`, `${base}-beauty`],
    signupDeliverables: [
      'Services, appointments & stylists in one dashboard',
      'Branded booking website in minutes',
      'QR check-in, reminders & analytics built in',
      'Payments, reviews & marketing tools',
    ],
    signupQuote:
      '"Clients book from our QR card now. Chair time, stylists and payments finally sit in one dashboard."',
    signupPersonName: 'Leah Mendes',
    signupPersonRole: 'Owner, Atelier Lume',
    signupPersonInitials: 'LM',
  },
  Clinic: {
    noun: 'clinic',
    nounPossessive: "clinic's",
    nameLabel: 'Clinic name',
    specialtyLabel: 'Specialty',
    specialtyPlaceholder: 'e.g. Dental, dermatology, general practice',
    specialtyPreview: 'Specialty',
    descriptionLabel: 'Clinic description',
    descriptionPlaceholder: 'Compassionate care with specialists you can trust.',
    websitePlaceholder: 'www.yourclinic.com',
    emailPlaceholder: 'hello@yourclinic.com',
    fallbackName: 'Your clinic',
    cta: 'Book an appointment',
    ctaShort: 'Book',
    secondaryCta: 'View services',
    welcomeLine: (name) => `Care you can trust at ${name}.`,
    flavorLine: (specialty) =>
      specialty ? `${specialty} care, focused on you.` : 'Care focused on you.',
    slugExtras: (base) => [`${base}-clinic`, `${base}-care`, `${base}-health`],
    signupDeliverables: [
      'Services, appointments & patients in one dashboard',
      'Branded clinic website in minutes',
      'QR check-in, reminders & analytics built in',
      'Payments, reviews & follow-up tools',
    ],
    signupQuote:
      '"Patients book from their phones. Our front desk stopped juggling three different tools."',
    signupPersonName: 'Dr. Nisha Varghese',
    signupPersonRole: 'Director, CarePoint Clinic',
    signupPersonInitials: 'NV',
  },
  Consultancy: {
    noun: 'consultancy',
    nounPossessive: "consultancy's",
    nameLabel: 'Consultancy name',
    specialtyLabel: 'Specialization',
    specialtyPlaceholder: 'e.g. Strategy, finance, operations',
    specialtyPreview: 'Specialization',
    descriptionLabel: 'Consultancy description',
    descriptionPlaceholder: 'Advisory that helps teams make clearer decisions.',
    websitePlaceholder: 'www.yourconsultancy.com',
    emailPlaceholder: 'hello@yourconsultancy.com',
    fallbackName: 'Your consultancy',
    cta: 'Book a consultation',
    ctaShort: 'Consult',
    secondaryCta: 'Our work',
    welcomeLine: (name) => `Partner with ${name}.`,
    flavorLine: (specialty) =>
      specialty ? `${specialty} expertise for growing teams.` : 'Expertise for growing teams.',
    slugExtras: (base) => [`${base}-consult`, `${base}-advisory`, `${base}-partners`],
    signupDeliverables: [
      'Services, leads & calendar in one dashboard',
      'Branded consultancy website in minutes',
      'QR business card, One Link & analytics',
      'Invoices, reviews & marketing tools',
    ],
    signupQuote:
      '"Prospects reach us from one link. Proposals, calendar and follow-ups finally share a home."',
    signupPersonName: 'Rohan Iyer',
    signupPersonRole: 'Principal, Northline Advisory',
    signupPersonInitials: 'RI',
  },
  Freelancer: {
    noun: 'profile',
    nounPossessive: "profile's",
    nameLabel: 'Brand / name',
    specialtyLabel: 'Craft',
    specialtyPlaceholder: 'e.g. Design, writing, development',
    specialtyPreview: 'Craft',
    descriptionLabel: 'About you',
    descriptionPlaceholder: 'Independent specialist for projects that need a dedicated expert.',
    websitePlaceholder: 'www.yourname.com',
    emailPlaceholder: 'hello@yourname.com',
    fallbackName: 'Your profile',
    cta: 'Hire me',
    ctaShort: 'Hire',
    secondaryCta: 'See work',
    welcomeLine: (name) => `Work with ${name}.`,
    flavorLine: (specialty) =>
      specialty ? `${specialty} for ambitious projects.` : 'Craft for ambitious projects.',
    slugExtras: (base) => [`${base}-studio`, `hi-${base}`, `${base}-works`],
    signupDeliverables: [
      'Portfolio, inquiries & calendar in one dashboard',
      'Branded profile site in minutes',
      'QR card, One Link & analytics built in',
      'Invoices, reviews & marketing tools',
    ],
    signupQuote:
      '"My QR card replaced a stack of paper ones. Clients book and pay without the email chase."',
    signupPersonName: 'Tara Gill',
    signupPersonRole: 'Independent designer',
    signupPersonInitials: 'TG',
  },
  'Professional Services': {
    noun: 'practice',
    nounPossessive: "practice's",
    nameLabel: 'Practice name',
    specialtyLabel: 'Practice area',
    specialtyPlaceholder: 'e.g. Legal, accounting, architecture',
    specialtyPreview: 'Practice',
    descriptionLabel: 'Practice description',
    descriptionPlaceholder: 'Professional services with clear advice and reliable delivery.',
    websitePlaceholder: 'www.yourpractice.com',
    emailPlaceholder: 'hello@yourpractice.com',
    fallbackName: 'Your practice',
    cta: 'Book a meeting',
    ctaShort: 'Book',
    secondaryCta: 'Our services',
    welcomeLine: (name) => `Work with ${name}.`,
    flavorLine: (specialty) =>
      specialty ? `${specialty} you can rely on.` : 'Advice you can rely on.',
    slugExtras: (base) => [`${base}-group`, `${base}-associates`, `${base}-partners`],
    signupDeliverables: [
      'Services, clients & appointments in one dashboard',
      'Branded practice website in minutes',
      'QR card, One Link & analytics built in',
      'Billing, reviews & marketing tools',
    ],
    signupQuote:
      '"Clients find our practice online and book from the site. Intake is cleaner than our old forms."',
    signupPersonName: 'Arjun Malhotra',
    signupPersonRole: 'Partner, Malhotra & Co.',
    signupPersonInitials: 'AM',
  },
  'Real Estate': {
    noun: 'agency',
    nounPossessive: "agency's",
    nameLabel: 'Agency name',
    specialtyLabel: 'Property types',
    specialtyPlaceholder: 'e.g. Residential, commercial, rentals',
    specialtyPreview: 'Properties',
    descriptionLabel: 'Agency description',
    descriptionPlaceholder: 'Helping buyers, sellers, and renters find the right property.',
    websitePlaceholder: 'www.youragency.com',
    emailPlaceholder: 'hello@youragency.com',
    fallbackName: 'Your agency',
    cta: 'Book a viewing',
    ctaShort: 'Enquire',
    secondaryCta: 'Listings',
    welcomeLine: (name) => `Find your next place with ${name}.`,
    flavorLine: (specialty) =>
      specialty
        ? `${specialty} across the neighborhoods you want.`
        : 'Homes across the neighborhoods you want.',
    slugExtras: (base) => [`${base}-homes`, `${base}-realty`, `${base}-estates`],
    signupDeliverables: [
      'Listings, inquiries & viewings in one dashboard',
      'Branded agency website in minutes',
      'QR listing cards, One Link & analytics',
      'Leads, reviews & marketing tools',
    ],
    signupQuote:
      '"Every listing has a QR now. Viewings and WhatsApp leads land in one place instead of three inboxes."',
    signupPersonName: 'Sana Qureshi',
    signupPersonRole: 'Broker, Qureshi Estates',
    signupPersonInitials: 'SQ',
  },
  Education: {
    noun: 'school',
    nounPossessive: "school's",
    nameLabel: 'School / institute name',
    specialtyLabel: 'Programs',
    specialtyPlaceholder: 'e.g. Tutoring, courses, workshops',
    specialtyPreview: 'Programs',
    descriptionLabel: 'About the institute',
    descriptionPlaceholder: 'Learning programs designed for real progress.',
    websitePlaceholder: 'www.yourschool.com',
    emailPlaceholder: 'hello@yourschool.com',
    fallbackName: 'Your school',
    cta: 'Enquire now',
    ctaShort: 'Enquire',
    secondaryCta: 'View programs',
    welcomeLine: (name) => `Learn with ${name}.`,
    flavorLine: (specialty) =>
      specialty ? `${specialty} for every learner.` : 'Programs for every learner.',
    slugExtras: (base) => [`${base}-academy`, `${base}-learn`, `${base}-institute`],
    signupDeliverables: [
      'Programs, enrollments & schedules in one dashboard',
      'Branded school website in minutes',
      'QR campus links, One Link & analytics',
      'Fees, reviews & marketing tools',
    ],
    signupQuote:
      '"Parents enrol from the site. Class lists and fee reminders stopped living in spreadsheets."',
    signupPersonName: 'Kavya Nair',
    signupPersonRole: 'Director, Nair Learning Studio',
    signupPersonInitials: 'KN',
  },
  'Fitness/Gym': {
    noun: 'gym',
    nounPossessive: "gym's",
    nameLabel: 'Gym name',
    specialtyLabel: 'Training focus',
    specialtyPlaceholder: 'e.g. Strength, yoga, HIIT',
    specialtyPreview: 'Training',
    descriptionLabel: 'Gym description',
    descriptionPlaceholder: 'Training, classes, and coaching in a welcoming space.',
    websitePlaceholder: 'www.yourgym.com',
    emailPlaceholder: 'hello@yourgym.com',
    fallbackName: 'Your gym',
    cta: 'Book a class',
    ctaShort: 'Book',
    secondaryCta: 'View classes',
    welcomeLine: (name) => `Train with ${name}.`,
    flavorLine: (specialty) =>
      specialty ? `${specialty} training that fits your life.` : 'Training that fits your life.',
    slugExtras: (base) => [`${base}-fitness`, `${base}-gym`, `${base}-train`],
    signupDeliverables: [
      'Classes, memberships & trainers in one dashboard',
      'Branded gym website in minutes',
      'QR check-in, bookings & analytics built in',
      'Payments, reviews & marketing tools',
    ],
    signupQuote:
      '"Members book classes from a QR at the desk. Attendance and memberships finally match."',
    signupPersonName: 'Dev Patel',
    signupPersonRole: 'Founder, Ironhouse',
    signupPersonInitials: 'DP',
  },
  'Local Business': {
    ...DEFAULT_COPY,
    slugExtras: (base) => [`${base}-local`, `${base}-hub`, `visit-${base}`],
  },
  'E-commerce Business': {
    noun: 'shop',
    nounPossessive: "shop's",
    nameLabel: 'Shop name',
    specialtyLabel: 'Product range',
    specialtyPlaceholder: 'e.g. Fashion, electronics, handmade',
    specialtyPreview: 'Products',
    descriptionLabel: 'Shop description',
    descriptionPlaceholder: 'An online shop with products people come back for.',
    websitePlaceholder: 'www.yourshop.com',
    emailPlaceholder: 'hello@yourshop.com',
    fallbackName: 'Your shop',
    cta: 'Shop now',
    ctaShort: 'Shop',
    secondaryCta: 'Browse catalog',
    welcomeLine: (name) => `Shop ${name}.`,
    flavorLine: (specialty) =>
      specialty ? `${specialty} delivered to your door.` : 'Products delivered to your door.',
    slugExtras: (base) => [`${base}-shop`, `buy-${base}`, `${base}-store`],
    signupDeliverables: [
      'Catalog, orders & customers in one dashboard',
      'Branded online shop in minutes',
      'QR storefront, One Link & analytics',
      'Payments, reviews & marketing tools',
    ],
    signupQuote:
      '"We went from Instagram DMs to a real shop site in an afternoon. Orders stopped getting lost."',
    signupPersonName: 'Isha Rao',
    signupPersonRole: 'Founder, Atelier Isha',
    signupPersonInitials: 'IR',
  },
  Other: {
    ...DEFAULT_COPY,
    nameLabel: 'Business name',
    specialtyLabel: 'What you offer',
    specialtyPlaceholder: 'Describe your offering',
  },
}

export function getBusinessCopy(category) {
  const specific = BY_CATEGORY[category]
  if (!specific) return { ...DEFAULT_COPY }
  return { ...DEFAULT_COPY, ...specific }
}

export function businessCategoryFromRestaurant(restaurant) {
  const settings = restaurant?.settings || {}
  return settings.businessCategory || settings.category || ''
}

export function locationPreviewLine(copy, specialty, city) {
  const parts = [specialty?.trim(), city?.trim()].filter(Boolean)
  if (parts.length) return parts.join(' · ')
  return `${copy.specialtyPreview} · City`
}
