export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  ACCOUNT_RECOVERY: '/account-recovery',
  NEW_PASSWORD: '/new-password',
  PASSWORD_UPDATED: '/password-updated',
  CREATE_ACCOUNT: '/create-account',
  ACCOUNT_THANKS: '/account-thanks',
  AWAITING_APPROVAL: '/awaiting-approval',
  RESTAURANT_SETUP: '/restaurant-setup',
  DOMAIN: '/domain',
  BRAND: '/brand',
  LAUNCH: '/launch',
  SETUP_REVIEW: '/review',
  ONBOARDING_PAYMENT: '/onboarding/payment',
  PAYMENT_THANKS: '/onboarding/payment-thanks',
  GO_LIVE: '/go-live',
  DASHBOARD: '/dashboard',
  RESTAURANT_PROFILE: '/restaurant-profile',
  DIRECTORY_LISTINGS: '/directory-listings',
  DIGITAL_BUSINESS_CARD: '/digital-business-card',
  BUSINESS_ID: '/business-id',
  DIGITAL_IDENTITY: '/digital-identity',
  DIGITAL_IDENTITY_FORM: '/digital-identity/form',
  MOBILE_APP: '/products/mobile-app',
  ONE_LINK: '/one-link',
  MENU: '/menu',
  ORDERS: '/orders',
  RESERVATIONS: '/reservations',
  TABLES: '/tables',
  STAFF: '/staff',
  CUSTOMERS: '/customers',
  ROLE_PERMISSIONS: '/role-permissions',
  ANALYTICS: '/analytics',
  PAYMENTS: '/payments',
  MARKETING: '/marketing',
  REVIEWS: '/reviews',
  POS_INTEGRATION: '/pos-integration',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  SETTINGS_EMAIL: '/settings/email',
  SETTINGS_PAYMENT: '/settings/payment',
  SETTINGS_USERS: '/settings/users',
  SETTINGS_BILLING: '/settings/billing',
  SETTINGS_SECURITY: '/settings/security',
  SETTINGS_API_KEYS: '/settings/api-keys',
  SETTINGS_BACKUP: '/settings/backup',
  SETTINGS_AUDIT: '/settings/audit',
  SETTINGS_PRIVACY: '/settings/privacy',
  PLATFORM_ADMIN: '/platform-admin',
  PLATFORM_PLANS: '/platform-admin/plans',
  PLATFORM_CUSTOMERS: '/platform-admin/customers',
  PLATFORM_CUSTOMER_ONBOARDING: '/platform-admin/customer-onboarding',
  PLATFORM_APPROVE: '/platform-admin/approve',
  PLATFORM_APPROVE_PROFILE: '/platform-admin/approve/:tenantId',
  PLATFORM_ACCOUNT_APPROVE: '/platform-admin/account-approve',
  PLATFORM_ACCOUNT_APPROVE_PROFILE: '/platform-admin/account-approve/:tenantId',
  PLATFORM_IDENTITIES: '/platform-admin/identities',
  PLATFORM_PRODUCTS: '/platform-admin/products',
  PLATFORM_NOTIFICATIONS: '/platform-admin/notifications',
  PLATFORM_AUDIT: '/platform-admin/audit',
  PLATFORM_STAFF: '/platform-admin/staff',
  PLATFORM_PROFESSIONAL: '/platform-admin/professional',
  PLATFORM_SETTINGS: '/platform-admin/settings',
  PLATFORM_SETTINGS_EMAIL: '/platform-admin/settings/email',
  PLATFORM_SETTINGS_PAYMENT: '/platform-admin/settings/payment',
  PLATFORM_SETTINGS_GOOGLE: '/platform-admin/settings/google',
  PLATFORM_SETTINGS_CATEGORIES: '/platform-admin/settings/categories',
  PLATFORM_SETTINGS_FLAGS: '/platform-admin/settings/flags',
  GUEST_ONE_LINK: '/l/:slug',
  GUEST_BUSINESS_CARD: '/c/:slug',
  GUEST_SITE: '/s/:slug',
  GUEST_SITE_PAGE: '/s/:slug/:page',
  GUEST_SITE_DISH: '/s/:slug/dish/:itemId',
  GUEST_SITE_TABLE: '/s/:slug/t/:tableCode',
  NOT_FOUND: '/404',
  UNAUTHORIZED: '/403',
}

export function platformApproveProfilePath(tenantId) {
  return `/platform-admin/account-approve/${tenantId}`
}

export function platformAccountApproveProfilePath(tenantId) {
  return `/platform-admin/account-approve/${tenantId}`
}
